FewMainDiamond/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FewMainDiamond.Controllers
{
    public class LayoutController : Controller
    {
        /// <summary>
        /// 布局通用公共部分
        /// </summary>
        /// <returns></returns>
        // GET: Layout
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 头部
        /// </summary>
        /// <returns></returns>
        public ActionResult Header()
        {
            return PartialView();
        }
        #region 网站公共部分

        public ActionResult Head()
        {
            return PartialView();
        }
        /// <summary>
        /// 导航
        /// </summary>
        /// <returns></returns>
        public ActionResult Nav()
        {

            return PartialView();
        }
        /// <summary>
        /// 底部
        /// </summary>
        /// <returns></returns>
        public ActionResult Footer()
        {
            return PartialView();
        }
        /// <summary>
        /// 右侧导航
        /// </summary>
        /// <returns></returns>
        public ActionResult RightFooterNav()
        {
            return PartialView();
        }


        #endregion
        #region 用户中心公共部分

        public ActionResult UserHeader()
        {
            return View();
        }

        public ActionResult UserLeftBar()
        {
            return View();
        }
        #endregion
    }
}

FewMainDiamond/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - -高级私人定制平台</title>
    <link href="~/Content/css/home.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    @*<link href="~/Content/css/diamond.css" rel="stylesheet" />*@
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/FewMain/common.base.js"></script>
    @RenderSection("scripts", required: false)
</head>
<body>
    <!--头部-->
    @{ Html.RenderAction("Header", "Layout",new {area=""});}

    @RenderBody()
    <!--底部-->
    @{ Html.RenderAction("Footer", "Layout", new { area = "" });}

    @*@Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/bootstrap")*@

</body>

</html>

FewMainDiamond/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/login.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/FewMain/common.base.js"></script>
    <script src="~/Scripts/layer-v3.0.1/layer/layer.js"></script>
    <script src="~/Scripts/FewMain/jquery.validate.ext.js"></script>
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="login">
        <div class="top">
            <a href="http://www.sunloves.com/"><img id="logo" src="/Content/images/login/user_logo.png"></a>
            <div class="right">
                <a class="theme-login" href="javascript:;">APP下载</a>
                <a class="theme-login2" href="javascript:;">微信客服</a>
            </div>
            <div class="theme-popover-mask"></div>
        </div>
        <!--------------------会员登陆--------------------------->

        @RenderBody()

        <!---------------------会员注册------------------------->

    </div>
    <!---APP下载--->
    <div class="theme-popover" style="display:none;">
        <div class="theme-poptit"><h3><b></b>APP下载</h3> <a class="close" title="关闭" href="javascript:;">×</a></div>
        <div class="theme_box"><img src="/Content/images/login/s_2.jpg"><p>您好，APP网站升级中，请稍后访问！<!--请扫描二维码下载APP登录QYdiamond官网--></p></div>
    </div>
    <!---微信客服--->
    <div class="theme-popover2" style="display:none;">
        <div class="theme-poptit2"><h3><b></b>微信客服</h3> <a class="close" title="关闭" href="javascript:;">×</a></div>
        <div class="theme_box"><img src="/Content/images/login/s_1.jpg"><p>请扫码添加QYdiamond客服为您服务</p></div>
    </div>
    @{ Html.RenderPartial("~/Views/Layout/RightFooterNav.cshtml");}
</body>
</html>

FewMainDiamond/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/usercenter/common.css" rel="stylesheet" />
    <link href="~/Content/css/usercenter/other.css" rel="stylesheet" />
    <link href="~/Content/css/usercenter/ucenter.css" rel="stylesheet" />
     


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    
    <script src="~/Scripts/FewMain/common.base.js"></script>
    <script>
        $(function() {
            $(".menubox a").click(function() {
                $(".menubox a").removeClass("hover");
                $(this).addClass("hover");
            })

            $(".menubox dt").click(function() {
                if ($(this).next().is("dd")) {
                    if ($(this).hasClass("click")) {
                        $(this).removeClass("click");
                        $(this).next("dd").slideDown();
                    } else {
                        $(this).addClass("click");
                        $(this).next("dd").slideUp();
                    }
                } else {
                    $(this).removeClass("click");
                }


            })
        })
    </script>
    @RenderSection("scripts", required: false)
</head>
<body>
    @{ Html.RenderAction("UserHeader", "Layout", new { area = "" });}
    <div class="clear mainbox">
        <div class="center">
            @{ Html.RenderAction("UserLeftBar", "Layout", new { area = "" });}
            @RenderBody()
        </div>
    </div>

    <!--底部-->
    @{ Html.RenderAction("Footer", "Layout", new { area = "" });}


</body>
</html>