FewMainDiamond/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FewMainDiamond.Controllers
{
    public class CartController : Controller
    {
        /// <summary>
        /// 购物车相关
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

FewMainDiamond/Controllers/DiamondController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using FewMain.Common;
using FewMain.Common.Cache;
using FewMain.Model;
using FewMain.Model.ParamModel;
using FewMain.Model.ViewModel;

namespace FewMainDiamond.Controllers
{
    public class DiamondController : Controller
    {

        public static HttpClient HttpClient
        {
            get
            {
                return CacheHelper.MemoryCache["httpClient"]==null?Login(): CacheHelper.MemoryCache["httpClient"] as HttpClient;
            }
        }


        // GET: Diamond
        public ActionResult Index()
        {
            return View();
        }  
        [HttpPost]
        public ActionResult GetDiamondData(SearchParam parms)
        {

            #region  构造参数
            parms.Shape = JsonHelper.ParseJSON<List<int>>(parms.StrShape);
            parms.Color = JsonHelper.ParseJSON<List<int>>(parms.StrColor);
            parms.Cut = JsonHelper.ParseJSON<List<int>>(parms.StrCut);
            parms.Clarity = JsonHelper.ParseJSON<List<int>>(parms.StrClarity);
            parms.Credentials = JsonHelper.ParseJSON<List<int>>(parms.StrCredentials);
            parms.Symmetry = JsonHelper.ParseJSON<List<int>>(parms.StrSymmetry);
            parms.Fluorescence = JsonHelper.ParseJSON<List<int>>(parms.StrFluorescence);
            parms.Polishing = JsonHelper.ParseJSON<List<int>>(parms.StrPolishing);
            #endregion

            string url= DiamondHelper.CustomUrl(parms);

          var model=  GetDiamondData(url);
            return Json(model);
        }

        [HttpGet]
        public ActionResult AddDiamondCart()
        {
            AddCart();
            return null;
        }

        

        #region 获取远程数据
        /// <summary>
        /// 登录远程网站
        /// </summary>
        public static HttpClient Login()
        {
            HttpClient httpClient = new HttpClient();
            httpClient.MaxResponseContentBufferSize = 256000;
            httpClient.DefaultRequestHeaders.Add("user-agent",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36");
            httpClient.DefaultRequestHeaders.Add("accept",
                "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
            httpClient.DefaultRequestHeaders.Add("Accept-Language", "zh-CN,zh;q=0.8,zh-TW;q=0.6");
            httpClient.DefaultRequestHeaders.Add("Cache-Control", "max-age=0");
            httpClient.DefaultRequestHeaders.Add("Connection", "keep-alive");
            httpClient.DefaultRequestHeaders.Add("Host", "www.888gia.com");
            httpClient.DefaultRequestHeaders.Add("Upgrade-Insecure-Requests", "1");
            httpClient.DefaultRequestHeaders.Add("Cookie", "kcdg_sessid=46qt3f3cmn5h67p7jsehnqntr2; kc_broadcast=1483774728; kcdg_kcdg_last=c4e32z3lDsvuZui7kYLy%2FNcZV3%2B9RmbRO%2BVo82SOHEDxBTMpGlFr");
            httpClient.DefaultRequestHeaders.Add("Origin", "http://www.888gia.com");
            httpClient.DefaultRequestHeaders.Add("Referer", "http://www.888gia.com/login");
            httpClient.DefaultRequestHeaders.Add("X-Requested-With", "XMLHttpRequest");
            httpClient.BaseAddress = new Uri("http://www.888gia.com/login");
            var uri = "http://www.888gia.com/login";

            var content = new FormUrlEncodedContent(new Dictionary<string, string>()
           {
               {"user_name", "nieq"},
               {"user_pwd", "ngq123456A"}
           });
            var response = httpClient.PostAsync(uri, content).Result;
            //return httpClient;
            #region 注释

            //var data = response.Headers.ToDictionary(t => t.Key);
            //data["Set-Cookie"].Value.First();//获取cookie 
            //string responseString = response.Content.ReadAsStringAsync().Result;
            return httpClient;

            #endregion

        }
        /// <summary>
        /// 根据链接获取当前页的字符串数据
        /// </summary>
        /// <param name="url">请求链接</param>
        /// <returns></returns>
        private static string GetHtml(string url)
        {
            HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);
            HttpClient.DefaultRequestHeaders.Referrer = new Uri("http://www.888gia.com/diamond/");
            response = HttpClient.GetAsync(new Uri(url)).Result;
            string result = response.Content.ReadAsStringAsync().Result;
            return result;
        }
        /// <summary>
        /// 获取当前页的数据
        /// </summary>
        /// <param name="url"></param>
        /// <returns></returns>
        private SKUSearchModel GetDiamondData(string url)
        {

            var PageInfo = GetHtml(url);
            #region 获取钻石数据
            string RegexStr =
                    "<tr class=\"list\"[\\w\\W]*?><td[\\w\\W]*?>(?<check>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<mark>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<onsale>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<datePro>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<shape>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<weight>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<clo>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<jingdu>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<cut>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<paoguang>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<duichen>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<yingguang>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<zhijing>[\\w\\W]*?)</td><td[\\w\\W]*?><a[\\w\\W]*?no=(?<giaNo>[\\w\\W]*?)&weight[\\w\\W]*?>(?<giaType>[\\w\\W]*?)</a></td><td[\\w\\W]*?>(?<pic>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<shipin>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<meijin>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<zhekou>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<rmb>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<kase>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<naise>[\\w\\W]*?)</td><td[\\w\\W]*?>(?<xuangou>[\\w\\W]*?)</td></tr>";
            SKUSearchModel model = new SKUSearchModel();
            List<SKUViewModel> list = new List<SKUViewModel>();

            PageInfo = PageInfo.Replace("\n", "").Replace("\r", "").Replace("\t", "").Replace("\\", "").Replace("<!-- 转换字段图片 -->", "").Replace("<!--                                管理员端                            -->", "");
            MatchCollection mc = Regex.Matches(PageInfo, RegexStr,
                RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.ExplicitCapture);
            foreach (Match item in mc)
            {
                list.Add(new SKUViewModel()
                {
                    #region 整理成数据
                    Shape = item.Groups["shape"].Value,
                    Weight = Convert.ToDecimal(StripHTMLToTEXT(item.Groups["weight"].Value)),
                    Color = item.Groups["clo"].Value,
                    Cut = item.Groups["cut"].Value,
                    Clarity = item.Groups["jingdu"].Value,
                    Polishing = item.Groups["paoguang"].Value,
                    Symmetry = item.Groups["duichen"].Value,
                    Fluorescence = item.Groups["yingguang"].Value,
                    SKUNo = "",
                    Price = Convert.ToDecimal(StripHTMLToTEXT(item.Groups["rmb"].Value)),
                    Milk = item.Groups["naise"].Value,
                    Coffee = item.Groups["kase"].Value,
                    ProNo = item.Groups["giaNo"].Value,
                    ProNoType = item.Groups["giaType"].Value,
                    DiaSize = item.Groups["zhijing"].Value,
                    Delivery = item.Groups["datePro"].Value,
                    State = item.Groups["onsale"].Value,
                    #endregion
                });

            }
            #endregion

            #region 获取数量信息

            string regexProInfo = "<div class=\"u-page-total\">(当前裸钻数量：(?<AllCount>[\\w\\W]*?) 颗[\\w\\W]*?显示(?<ShowCount>[\\w\\W]*?)颗)</div>";
            MatchCollection mcPro = Regex.Matches(PageInfo, regexProInfo,
               RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.ExplicitCapture);
            foreach (Match item in mcPro)
            {
                model.Count = Convert.ToInt32(StripHTMLToTEXT(item.Groups["AllCount"].Value));
                model.PageCount = Math.Ceiling(Convert.ToDecimal(model.Count/50)).ToInt();
                model.ShowCount= Convert.ToInt32(StripHTMLToTEXT(item.Groups["ShowCount"].Value));
                model.DiamondInfo = item.Groups[0].Value;
            }
            #endregion
            model.PageList = list;
            return model;

        }

        /// <summary>
        /// 添加到购物车 单个产品
        /// </summary>
        /// <param name="diaSN"></param>
        /// <returns></returns>
        private static string AddCart(string diaSN)
        {
           

            HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);
            HttpClient.DefaultRequestHeaders.Referrer = new Uri("http://www.888gia.com/diamond/");
            response = HttpClient.GetAsync(new Uri(" http://www.888gia.com/consumer/cart/add/"+ diaSN)).Result;
            string result = response.Content.ReadAsStringAsync().Result;
            return result;
            // HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);
            // HttpClient.DefaultRequestHeaders.Referrer = new Uri("http://www.888gia.com/diamond/");
            // var uri = "http://www.888gia.com"+ "/consumer/cart/add";
            // var content = new FormUrlEncodedContent(new Dictionary<string, string>()
            //{
            //    {"dids", "[\"15791152\", \"15682069\", \"14450356\"]"},
            //});
            // //var response = HttpClient.PostAsync(uri, content).Result;
            // response = HttpClient.PostAsync(uri, content).Result;
            // var dd= response.Content.ReadAsStringAsync().Result;
            return "";

        }

        public static string StripHTMLToTEXT(string strHtml)
        {

FewMainDiamond/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FewMainDiamond.Controllers
{
    public class LayoutController : Controller
    {
        /// <summary>
        /// 布局通用公共部分
        /// </summary>
        /// <returns></returns>
        // GET: Layout
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 头部
        /// </summary>
        /// <returns></returns>
        public ActionResult Header()
        {
            return PartialView();
        }
        #region 网站公共部分

        public ActionResult Head()
        {
            return PartialView();
        }
        /// <summary>
        /// 导航
        /// </summary>
        /// <returns></returns>
        public ActionResult Nav()
        {

            return PartialView();
        }
        /// <summary>
        /// 底部
        /// </summary>
        /// <returns></returns>
        public ActionResult Footer()
        {
            return PartialView();
        }
        /// <summary>
        /// 右侧导航
        /// </summary>
        /// <returns></returns>
        public ActionResult RightFooterNav()
        {
            return PartialView();
        }


        #endregion
        #region 用户中心公共部分

        public ActionResult UserHeader()
        {
            return View();
        }

        public ActionResult UserLeftBar()
        {
            return View();
        }
        #endregion
    }
}

FewMainDiamond/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FewMainDiamond.Controllers
{
    public class MemberController : Controller
    {
        // GET: Member
        public ActionResult Index()
        {
            return View();
        }
    }
}

FewMainDiamond/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FewMainDiamond.Controllers
{
    /// <summary>
    /// 订单相关
    /// </summary>
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
    }
}

FewMainDiamond/Views/Layout/Footer.cshtml
<!--底部开始-->
<div class="footer">
    <div class="top">
        <ul style="width:220px">
            <img src="~/Content/images/base/bot_02.png" />
        </ul>
        <ul>
            <h3><a href="http://www.sunloves.com/info/index/nid/1.html" target="_blank">关于我们</a></h3>
            <li><a href="http://www.sunloves.com/info/index/nid/1.html" target="_blank">品牌简介</a></li>
            <li><a href="http://www.sunloves.com/cover/index/nid/6.html" target="_blank">市场合作</a></li>
            <li><a href="http://www.sunloves.com/list/index/nid/8.html" target="_blank">最新动态</a></li>
            <li><a href="http://www.sunloves.com/contact/index/nid/9.html" target="_blank">联系我们</a></li>
        </ul>
        <ul>
            <h3><a href="http://www.sunloves.com/news/index/nid/34.html" target="_blank">购物指南</a></h3>
            <li><a href="http://www.sunloves.com/content/index/nid/34/id/61.html" target="_blank">购物流程</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/34/id/28.html" target="_blank">订单查询</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/34/id/27.html" target="_blank">在线下单</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/34/id/26.html" target="_blank">常见问题</a></li>
        </ul>
        <ul>
            <h3><a href="http://www.sunloves.com/news/index/nid/35.html" target="_blank">支付方式</a></h3>
            <li><a href="http://www.sunloves.com/content/index/nid/35/id/60.html" target="_blank">第三方支付</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/35/id/59.html" target="_blank">银行汇款</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/35/id/33.html" target="_blank">微信支付</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/35/id/32.html" target="_blank">支付宝支付</a></li>
        </ul>
        <ul>
            <h3><a href="http://www.sunloves.com/news/index/nid/36.html" target="_blank">配送方式</a></h3>
            <li><a href="http://www.sunloves.com/content/index/nid/36/id/58.html" target="_blank">定制店自提</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/36/id/31.html" target="_blank">顺丰保价快递</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/36/id/30.html" target="_blank">专人配送</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/36/id/29.html" target="_blank">包装代采购</a></li>
        </ul>
        <ul>
            <h3><a href="http://www.sunloves.com/news/index/nid/37.html" target="_blank">售后服务</a></h3>
            <li><a href="http://www.sunloves.com/content/index/nid/37/id/37.html" target="_blank">免费清洗</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/37/id/36.html" target="_blank">戒圈修改</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/37/id/35.html" target="_blank">终身保修</a></li>
            <li><a href="http://www.sunloves.com/content/index/nid/37/id/34.html" target="_blank">优惠改款</a></li>
        </ul>
        <div class="right">
            <img src="~/Content/images/base/bottom1.png" />
        </div>
        @*<div class="bot"><img src="~/Content/images/base/bot_03.png" /></div>*@
    </div>

    <div class="bot">

        <div class="box">
            <p>
                <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=2770491440&amp;site=qq&amp;menu=yes">友情链接</a> | <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=2559364384&amp;site=qq&amp;menu=yes">在线投诉</a> | Copyright © 2011-2016 All rights reserved   深圳市尚爱珠宝有限公司  网站备案号： <a href="http://www.miitbeian.gov.cn/" target="_blank">粤ICP备12069075号-4</a>

            </p>
            <p>
                <a href="#" target="_blank">阿里巴巴</a> |
                <a href="#" target="_blank">淘宝</a> |
                <a href="#" target="_blank">天猫</a> |
                <a href="#" target="_blank">百度</a> |
                <a href="http://www.163.com/" target="_blank">网易</a> |
                <a href="http://www.sohu.com/" target="_blank">搜狐</a> |
                <a href="http://www.qq.com/" target="_blank">腾讯</a> |
                <a href="http://www.360.com/" target="_blank">360</a>

            </p>
        </div>
        <div class="img">
            <img src="~/Content/images/base/bot_07.png" />
            <img src="~/Content/images/base/bot_09.png" />
            <img src="~/Content/images/base/bot_11.png" />
            <img src="~/Content/images/base/bot_13.png" />
            <img src="~/Content/images/base/bot_15.png" />
        </div>

    </div>


</div>
<!--底部结束-->

<!--右侧客服导航开始-->
@{ Html.RenderPartial("RightFooterNav");}
<!--右侧客服导航结束-->

FewMainDiamond/Views/Layout/Head.cshtml
@using FewMain.WebHelper.CurrentContext
<!--头部开始-->
<div class="header">
    <div class="top" name="top" id="top">
        <ul>
            <div class="logo"><a href="http://www.sunloves.com/">@*<img src="~/Content/images/base/logo.png" title="尚爱珠宝" />*@</a></div>
            <li class="w"><a class="theme-login2" href="javascript:;">关注尚爱</a></li>

            @if (CurrentUserContext.Current.IsLogin)
            {
                <li><a href="@Url.Action("Index","Cart")" target="_blank">您的购物车中有<b>0</b>件商品</a></li>

                <li><a href="@Url.Action("LoginOut","Account")" target="_top">退出</a></li>
                <li><a href="@Url.Action("LoginOut","Account")" target="_blank">会员中心</a></li>
                <li>您好<b>@CurrentUserContext.Current.UserName</b>，欢迎来到尚爱珠宝品牌官网!</li>
            }
            else
            {
                <li><a href="@Url.Action("Register","Account")" target="_blank">注册</a></li>
                <li><a href="@Url.Action("Login","Account")" target="_blank">登陆</a></li>

                <li>您好<b></b>，欢迎来到尚爱珠宝品牌官网!</li>
            }

            <div class="theme-popover-mask"></div>
        </ul>
    </div>
    <div class="head">

        <div class="l_right"><img src="~/Content/images/base/l_right.jpg" title="" alt="" /></div>
        <div class="right"><img src="~/Content/images/base/phone.jpg" /></div>

    </div>

    <!---APP下载--->
    <div class="theme-popover" style="display:none;">
       @* <div class="theme-poptit"><h3><b></b>APP下载</h3> <a class="close" title="关闭" href="javascript:;">×</a></div>
    <div class="theme_box"><img src="~/Content/images/base/s_2.jpg" /><p>您好，欢迎下载尚爱珠宝APP《安卓版》！<!--请扫描二维码下载APP登录QYdiamond官网--></p></div>*@
    </div>
    <!---微信客服--->
    <div class="theme-popover2" style="display:none;">
        <div class="theme-poptit2"><h3><b></b>关注尚爱微信</h3> <a class="close" title="关闭" href="javascript:;">×</a></div>
        <div class="theme_box">@*<img src="~/Content/images/base/s_1.jpg" />*@<p>请扫码添加sunloves客服为您服务</p></div>
    </div>
</div>
<!--头部结束-->

FewMainDiamond/Views/Layout/RightFooterNav.cshtml
@using FewMain.WebHelper.CurrentContext
<!--右侧客服导航开始-->
<div class="chat_f1">
    <div class="chat_f1_expr" style="height: 800px; display: block;">
        <!------------>
        <div class="list">
            <b><a href="@Url.Action("Index","Member")"><img src="~/Content/images/base/1_03.png" /></a></b>
            @if (CurrentUserContext.Current.IsLogin)
            {
                <div class="detail" style="width: 136px; margin-left: -136px; height: 200px;">
                    <span class="mem">
                        <img src="~/Content/images/base/1_01.png" />
                        <li><a href="@Url.Action("LoginOut","Account")" target="_top">退出</a></li>
                        <li><a href="@Url.Action("Index","Member")" target="_blank">会员中心</a></li>
                    </span>
                </div>
            }
            else
            {
                <div class="detail" style="width: 136px; margin-left: -136px; height: 200px; display: none;">
                    <span class="mem">
                        <img src="http://www.sunloves.com/Public/home/images/qq/1_01.png">
                        <li><a href="@Url.Action("Register", "Account")" target="_blank">注册</a></li>
                        <li><a href="@Url.Action("Login","Account")" target="_blank">登陆</a></li>
                    </span>
                </div>
            }
           
            
        </div>
        <!------------>
        <div class="list kf1">
            <b><a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=2047753273&amp;site=qq&amp;menu=yes"><img src="~/Content/images/base/1_11.png" /></a></b>
            <div class="detail" style="width:150px;  margin-left:-150px; margin-top:-100px;">
                <span class="kf">
                    <h6>客服中心</h6>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=2047753273&amp;site=qq&amp;menu=yes" class="one">客服咨询</a>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=2047753273&amp;site=qq&amp;menu=yes" class="one">客服咨询</a>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=929327063&amp;site=qq&amp;menu=yes" class="one">客服咨询</a>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=2559364384&amp;site=qq&amp;menu=yes" class="two">用户反馈</a>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=2559364384&amp;site=qq&amp;menu=yes" class="two">售后服务</a>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=929327063&amp;site=qq&amp;menu=yes" class="two">招商部经理</a>
                </span>
            </div>
        </div>
        <!------------>
        <div class="list">
            <b><a target="_blank" href="@Url.Action("index","Cart")"><img src="~/Content/images/base/1_05.png" /></a></b>
            <div class="detail" style="width:136px;  margin-left:-136px; ">
                <span class="mem" style="height:120px;">
                    购物车数量为
                    <b> 0&nbsp;<font style="font-weight:lighter">件商品</font></b>
                    <li><a href="@Url.Action("index","Cart")" target="_blank">购物车</a> </li>
                </span>
            </div>
        </div>
        <!------------>
        <div class="list">
            <b><a target="_blank" href="@Url.Action("Index","Order")"><img src="~/Content/images/base/1_07.png" /></a></b>
            <div class="detail">
                <span><a target="_blank" href="@Url.Action("Index","Order")">我的订单</a></span>
            </div>
        </div>
        <!------------>
        <!---------------------------------------------------------------->
        <div class="list" style="margin-top:160px;">
            <b>
                <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=657525650&amp;site=qq&amp;menu=yes"><img src="~/Content/images/base/1_13.png" /></a>
            </b>
            <div class="detail">
                <span>
                    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=657525650&amp;site=qq&amp;menu=yes">用户反馈</a>
                </span>
            </div>
        </div>

        <div class="list">
            <b>
                <a target="_blank" href="http://www.sunloves.com/diamond/index/nid/2.html"><img src="~/Content/images/base/1_14.png" /></a>
            </b>
            <div class="detail" style="width:200px; margin-top:-210px; margin-left:-200px; height:210px;">
                <!-- JiaThis Button BEGIN -->
                <div id="jiathis_sers" class="jiadiv_02">
                    <h6>分享给我的好友们</h6>
                    <a class="jiatitle" onclick="jiathis_sendto(&#39;tsina&#39;);return false;" href="javascript:;"><img src="~/Content/images/base/f1.png" />新浪微博</a>
                    <a class="jiatitle" onclick="jiathis_sendto(&#39;weixin&#39;);return false;" href="javascript:;"><img src="~/Content/images/base/f2.png" />微信</a>
                    <a class="jiatitle" onclick="jiathis_sendto(&#39;qzone&#39;);return false;" href="javascript:;"><img src="~/Content/images/base/f8.png" />QQ空间</a>
                    <a class="jiatitle" onclick="jiathis_sendto(&#39;tqq&#39;);return false;" href="javascript:;"><img src="~/Content/images/base/f4.png" />腾讯微博</a>
                    <a class="jiatitle" onclick="jiathis_sendto(&#39;renren&#39;);return false;" href="javascript:;"><img src="~/Content/images/base/f10.png" />人人网</a>
                    <a class="jiatitle" onclick="jiathis_sendto(&#39;cqq&#39;);return false;" href="javascript:;"><img src="~/Content/images/base/f5.png" />QQ好友</a>
                </div>
                <!-- JiaThis Button END -->
            </div>
        </div>
        <!------------>
        <div class="list">
            <b><img src="~/Content/images/base/1_15.png" /></b>
            <div class="detail" style="width:136px; margin-top:-260px; margin-left:-136px; height:200px;">
                <span>
                    <img src="~/Content/images/base/ws.png" />
                </span>
            </div>
        </div>
        <!------------>
        <div class="list">

            <b><a href="#top" name="top"><img src="~/Content/images/base/1_18.png" /></a></b>
            <div class="detail"><span><a href="#top" name="top">返回顶部</a></span></div>
        </div>
    </div>
</div>
<!--右侧客服导航结束-->

FewMainDiamond/Views/Layout/UserLeftBar.cshtml
        <dl class="menubox white left">
            <dt>购物<span></span></dt>
            <dd>
                <ul class="menubox-content">
                    <li>
                        <a class="hover" href="@Url.Action("Index","Cart")">我的购物车</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Collection",new {area="User"})">我的收藏</a>
                    </li>

                </ul>
            </dd>
            <dt>订单中心<span></span></dt>
            <dd>
                <ul class="menubox-content">
                    <li>
                        <a href="@Url.Action("Index","Order",new {area="User"})">我的订单</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Appraise","Order",new { area="User"})">我的评价</a>
                    </li>
                </ul>
            </dd>

            <dt>账户和安全<span></span></dt>
            <dd>
                <ul class="menubox-content">
                    <li>
                        <a href="@Url.Action("Index","Information",new {area="User"})">个人资料</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ModifyPwd","Binding",new {area="User"})">密码修改</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Mobile","Binding",new {area="User"})">绑定手机</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Email","Binding",new {area="User"})">绑定邮箱</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Address",new {area="User"})">地址管理</a>
                    </li>
                </ul>
            </dd>
        </dl>
 